package src;

/** Datablock name (lowercased) -> dts path, for purely-cosmetic PlatinumQuest static props
	that need nothing beyond `PQProp` (no bespoke behavior class). Used as a fallback by
	`DatablockRegistry.resolveShape` once the ordered match list misses. */
class PQDecorations {
	public static var paths:Map<String, String> = [
		// Fences
		"fence_1tileslength" => "data/shapes_pq/scenery/fence/fence_1tileslength.dts",
		"fence_2tileslength" => "data/shapes_pq/scenery/fence/fence_2tileslength.dts",
		"fence_3tileslength" => "data/shapes_pq/scenery/fence/fence_3tileslength.dts",
		"fence_4tileslength" => "data/shapes_pq/scenery/fence/fence_4tileslength.dts",
		"fence_5tileslength" => "data/shapes_pq/scenery/fence/fence_5tileslength.dts",
		"fencepole" => "data/shapes_pq/scenery/fence/fence_pole.dts",
		"metal_end_fence_short" => "data/shapes_pq/scenery/fence/metalendfenceshort.dts",
		"metal_start_fence_short" => "data/shapes_pq/scenery/fence/metalstartfenceshort.dts",
		"metal_pole_fence_short" => "data/shapes_pq/scenery/fence/metalpolefencelong.dts",
		"metal_end_fence_tall" => "data/shapes_pq/scenery/fence/metalendfencetall.dts",
		"metal_start_fence_tall" => "data/shapes_pq/scenery/fence/metalstartfencetall.dts",
		"metal_pole_fence_tall" => "data/shapes_pq/scenery/fence/metalpolefenceshort.dts",
		"plastic_end_fence_short" => "data/shapes_pq/scenery/fence/plasticendfenceshort.dts",
		"plastic_start_fence_short" => "data/shapes_pq/scenery/fence/plasticstartfenceshort.dts",
		"plastic_pole_fence_short" => "data/shapes_pq/scenery/fence/plasticpolefencelong.dts",
		"plastic_end_fence_tall" => "data/shapes_pq/scenery/fence/plasticendfencetall.dts",
		"plastic_start_fence_tall" => "data/shapes_pq/scenery/fence/plasticstartfencetall.dts",
		"plastic_pole_fence_tall" => "data/shapes_pq/scenery/fence/plasticpolefenceshort.dts",

		// Nature / plants
		"plant01" => "data/shapes_pq/scenery/nature/plant.dts",
		"fern01" => "data/shapes_pq/scenery/nature/fern01.dts",
		"flowers" => "data/shapes_pq/scenery/nature/flowers.dts",
		"tulip" => "data/shapes_pq/scenery/nature/tulip.dts",
		"scarce_tulips" => "data/shapes_pq/scenery/nature/scarce_tulip.dts",
		"dense_tulips" => "data/shapes_pq/scenery/nature/dense_tulip.dts",
		"scarce_tulips_3tiles" => "data/shapes_pq/scenery/nature/scarce_tulip_3tiles.dts",
		"effectplant" => "data/shapes_pq/other/effectplant.dts",
		"grass" => "data/shapes_pq/scenery/nature/grass.dts",
		"largegrass" => "data/shapes_pq/scenery/nature/grasslarge.dts",
		"grass02small" => "data/shapes_pq/scenery/nature/scarce_grass_small.dts",
		"grass02densesmall" => "data/shapes_pq/scenery/nature/dense_grass_small.dts",
		"grass02denselarge" => "data/shapes_pq/scenery/nature/dense_grass_large.dts",
		"naturalplant" => "data/shapes_pq/scenery/nature/naturalplant.dts",
		"vineswidelong" => "data/shapes_pq/scenery/nature/vineswidelong.dts",
		"vineswideshort" => "data/shapes_pq/scenery/nature/vineswideshort.dts",
		"vinesthinlong" => "data/shapes_pq/scenery/nature/vinesthinlong.dts",
		"vinesthinshort" => "data/shapes_pq/scenery/nature/vinesthinshort.dts",
		"tree01" => "data/shapes_pq/scenery/nature/tree01.dts",
		"tree02" => "data/shapes_pq/scenery/nature/tree02.dts",
		"tree03" => "data/shapes_pq/scenery/nature/tree03.dts",
		"treebare01" => "data/shapes_pq/scenery/nature/treebare01.dts",
		"treebare02" => "data/shapes_pq/scenery/nature/treebare02.dts",
		"treebare03" => "data/shapes_pq/scenery/nature/treebare03.dts",
		"rock01" => "data/shapes_pq/scenery/nature/rock01.dts",
		"rock02" => "data/shapes_pq/scenery/nature/rock02.dts",
		"rock03" => "data/shapes_pq/scenery/nature/rock03.dts",
		"rock04" => "data/shapes_pq/scenery/nature/rock04.dts",
		"sandhill01" => "data/shapes_pq/scenery/obstacles/sandhill1.dts",
		"sandhill02" => "data/shapes_pq/scenery/obstacles/sandhill2.dts",
		"sandhill03" => "data/shapes_pq/scenery/obstacles/sandhill3.dts",
		"sandhill04" => "data/shapes_pq/scenery/obstacles/sandhill4.dts",
		"sandhill05" => "data/shapes_pq/scenery/obstacles/sandhill5.dts",
		"asteroid" => "data/shapes_pq/levelparts/asteroid.dts",
		"astrolabe" => "data/shapes_mbu/astrolabe/astrolabe.dts",
		"iceslick1" => "data/shapes_pq/gameplay/hazards/iceslick1.dts",
		"iceslick2" => "data/shapes_pq/gameplay/hazards/iceslick2.dts",
		"iceslick3" => "data/shapes_pq/gameplay/hazards/iceslick3.dts",
		"iceslick4" => "data/shapes_pq/gameplay/hazards/iceslick4.dts",

		// Graffiti (all decal-like, zdrop in source)
		"marble_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_marble.dts",
		"superjump_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_sj.dts",
		"cannon_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_cannon.dts",
		"pq_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_pq.dts",
		"pqrulez_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_pqrulez.dts",
		"logo_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_logo.dts",
		"gg_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_gg.dts",
		"gglogo_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_gglogo.dts",
		"philsempire_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_pe.dts",
		"tornado_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_tornado.dts",
		"hourglass_graffiti" => "data/shapes_pq/scenery/graffiti/graffiti_hourglass.dts",

		// Signs
		"sign01" => "data/shapes_pq/scenery/signs/sign01.dts",
		"sign02" => "data/shapes_pq/scenery/signs/sign02.dts",
		"roadsignyellow" => "data/shapes_pq/scenery/signs/roadsignyellow.dts",
		"roadsignred" => "data/shapes_pq/scenery/signs/roadsignred.dts",
		"constructonroadsignyellow" => "data/shapes_pq/scenery/signs/constructonroadsignyellow.dts",
		"constructonroadsignred" => "data/shapes_pq/scenery/signs/constructonroadsignred.dts",
		"detourroadsignyellow" => "data/shapes_pq/scenery/signs/detourroadsignyellow.dts",
		"detourroadsignred" => "data/shapes_pq/scenery/signs/detourroadsignred.dts",
		"cardboardsign" => "data/shapes_pq/gameplay/signs/threefolder.dts",
		"carboardsign_l" => "data/shapes_pq/gameplay/signs/threefolderleftsign.dts",
		"carboardsign_r" => "data/shapes_pq/gameplay/signs/threefolderrightsign.dts",
		"carboardsign_up_l" => "data/shapes_pq/gameplay/signs/threefolderupsignl.dts",
		"carboardsign_up_r" => "data/shapes_pq/gameplay/signs/threefolderupsignr.dts",
		"carboardsign_down_l" => "data/shapes_pq/gameplay/signs/threefolderdownsignl.dts",
		"carboardsign_down_r" => "data/shapes_pq/gameplay/signs/threefolderdownsignr.dts",
		"regularfinishlinesign" => "data/shapes_pq/gameplay/signs/regularfinishsign.dts",
		"consfinishlinesign" => "data/shapes_pq/gameplay/signs/consfinishlinesign.dts",
		"consfinishlinesignnocrane" => "data/shapes_pq/gameplay/signs/consfinishlinesignnocrane.dts",
		"naturefinishlinesignlight" => "data/shapes_pq/gameplay/signs/naturfinishlinesignlight.dts",
		"naturefinishlinesigndark" => "data/shapes_pq/gameplay/signs/naturfinishlinesigndark.dts",

		// Windows
		"window01" => "data/shapes_pq/scenery/windows/window01.dts",
		"window01_light" => "data/shapes_pq/scenery/windows/window01_light.dts",
		"window01_3x3" => "data/shapes_pq/scenery/windows/window01_3x3.dts",
		"window01_3x3_light" => "data/shapes_pq/scenery/windows/window01_3x3_light.dts",
		"window01_6x6" => "data/shapes_pq/scenery/windows/window01_6x6.dts",
		"window01_6x6_light" => "data/shapes_pq/scenery/windows/window01_6x6_light.dts",
		"window01_12x12" => "data/shapes_pq/scenery/windows/window01_12x12.dts",
		"window01_12x12_light" => "data/shapes_pq/scenery/windows/window01_12x12_light.dts",
		"window01_3x12" => "data/shapes_pq/scenery/windows/window01_3x12.dts",
		"window01_3x12_light" => "data/shapes_pq/scenery/windows/window01_3x12_light.dts",
		"window01o" => "data/shapes_pq/scenery/windows/window01o.dts",
		"window01o_light" => "data/shapes_pq/scenery/windows/window01o_light.dts",
		"window01o_3x3" => "data/shapes_pq/scenery/windows/window01o_3x3.dts",
		"window01o_3x3_light" => "data/shapes_pq/scenery/windows/window01o_3x3_light.dts",
		"window01o_6x6" => "data/shapes_pq/scenery/windows/window01o_6x6.dts",
		"window01o_6x6_light" => "data/shapes_pq/scenery/windows/window01o_6x6_light.dts",
		"window02" => "data/shapes_pq/scenery/windows/window01.dts", // matches a literal bug in PQ's own script (Window02's shapeFile points at Window01.dts)
		"window02_light" => "data/shapes_pq/scenery/windows/window02_light.dts",
		"window02_3x3" => "data/shapes_pq/scenery/windows/window02_3x3.dts",
		"window02_3x3_light" => "data/shapes_pq/scenery/windows/window02_3x3_light.dts",
		"window02o" => "data/shapes_pq/scenery/windows/window02o.dts",
		"window02o_light" => "data/shapes_pq/scenery/windows/window02o_light.dts",
		"window02o_3x3" => "data/shapes_pq/scenery/windows/window02o_3x3.dts",
		"window02o_3x3_light" => "data/shapes_pq/scenery/windows/window02o_3x3_light.dts",
		"window03" => "data/shapes_pq/scenery/windows/window03.dts",
		"window03_light" => "data/shapes_pq/scenery/windows/window03_light.dts",
		"window03_3x3" => "data/shapes_pq/scenery/windows/window03_3x3.dts",
		"window03_3x3_light" => "data/shapes_pq/scenery/windows/window03_3x3_light.dts",
		"window03o" => "data/shapes_pq/scenery/windows/window03o.dts",
		"window03o_light" => "data/shapes_pq/scenery/windows/window03o_light.dts",
		"window03o_3x3" => "data/shapes_pq/scenery/windows/window03o_3x3.dts",
		"window03o_3x3_light" => "data/shapes_pq/scenery/windows/window03o_3x3_light.dts",
		"window04" => "data/shapes_pq/scenery/windows/window04.dts",
		"window04_light" => "data/shapes_pq/scenery/windows/window04_light.dts",
		"window04_3x3" => "data/shapes_pq/scenery/windows/window04_3x3.dts",
		"window04_3x3_light" => "data/shapes_pq/scenery/windows/window04_3x3_light.dts",
		"window04o" => "data/shapes_pq/scenery/windows/window04o.dts",
		"window04o_light" => "data/shapes_pq/scenery/windows/window04o_light.dts",
		"window04o_3x3" => "data/shapes_pq/scenery/windows/window04o_3x3.dts",
		"window04o_3x3_light" => "data/shapes_pq/scenery/windows/window04o_3x3_light.dts",

		// Misc
		"marblius" => "data/shapes_pq/levelparts/marblius.dts",
		"spectrum" => "data/shapes_pq/other/spectrum.dts",
		"spectrum2" => "data/shapes_pq/other/spectrum_sub.dts",
		"spectrum3" => "data/shapes_pq/other/spectrum_unlit.dts",
		"spectrum4" => "data/shapes_pq/other/spectrum_sub_unlit.dts",
		"soundstage" => "data/shapes_pq/other/soundstage.dts",
		"sillyglass" => "data/shapes_pq/gameplay/pads/silly_cp_glass.dts",
		"pillowonuse" => "data/shapes_pq/gameplay/powerups/pillow2.dts",
		"barrier" => "data/shapes_pq/scenery/construction/detourbars.dts",
		"cloud48" => "data/shapes_pq/scenery/clouds/cloud48.dts",
		"cloud36" => "data/shapes_pq/scenery/clouds/cloud36.dts",
		"cloud24" => "data/shapes_pq/scenery/clouds/cloud24.dts",
		"flatlargeclouds" => "data/shapes_pq/scenery/clouds/flatlarge.dts",
		"orbitingclouds" => "data/shapes_pq/scenery/clouds/cloudscape.dts",

		// Halloween
		"candybasket" => "data/shapes/halloween/candy_basket.dts",
		"haybale" => "data/shapes/halloween/hay_bale.dts",
		"haycube" => "data/shapes/halloween/hay_cube.dts",
		"haystack" => "data/shapes/halloween/hay_stack.dts",
		"candypilebig" => "data/shapes/halloween/pile-o-candy_big.dts",
		"candypilesmall" => "data/shapes/halloween/pile-o-candy_small.dts",
		"pumpkinscary" => "data/shapes/halloween/pumpkin.dts",
		"pumpkinregular" => "data/shapes/halloween/pumpkin__normal_bad.dts",
		"pumpkindent" => "data/shapes/halloween/pumpkin_bad.dts",
		"pumpkinbigdent" => "data/shapes/halloween/pumpkin_bad_bad.dts",
		"pumpkinscarynolight" => "data/shapes/halloween/pumpkin_scarry_bad.dts",
		"bat" => "data/shapes/halloween/bat.dts",
		"candycorn" => "data/shapes/halloween/candy_corn.dts",
		"candycollectable" => "data/shapes/halloween/candy_collectable.dts",
		"mrskeletal" => "data/shapes/halloween/spooky_skeleton.dts",
		"mrskeletalsad" => "data/shapes/halloween/sad_skeleton.dts",
		"mrskeletaltired" => "data/shapes/halloween/tired_skeleton.dts",
		"cobwebs" => "data/shapes/halloween/spider_web.dts",
		"witchhat" => "data/shapes/halloween/witchhatnormal.dts",
		"witchhatbig" => "data/shapes/halloween/witchhatbig.dts",
		"vermontry" => "data/shapes/halloween/vermontry/vermontry.dts",
		"halloweenlights2u" => "data/shapes/halloween/halloweenlights_2t.dts",
		"halloweenlights3u" => "data/shapes/halloween/halloweenlights_3t.dts",
		"halloweenlights6u" => "data/shapes/halloween/halloweenlights_6t.dts",
		"halloweenlights9u" => "data/shapes/halloween/halloweenlights_9t.dts",

		// Christmas
		"santahatimage" => "data/shapes/xmas/santahat.dts",
		"santahatlargeimage" => "data/shapes/xmas/santahatmega.dts",
		"candycane" => "data/shapes/xmas/candycane.dts",
		"christmaslights2t" => "data/shapes/xmas/christmaslights_2t.dts",
		"christmaslights3t" => "data/shapes/xmas/christmaslights_3t.dts",
		"christmaslights6t" => "data/shapes/xmas/christmaslights_6t.dts",
		"christmaslights9t" => "data/shapes/xmas/christmaslights_9t.dts",
		"christmastreedecorated" => "data/shapes/xmas/christmastreedecorated.dts",
		"christmastreenormal" => "data/shapes/xmas/christmastreenormal.dts",
		"christmastreenormaldark" => "data/shapes/xmas/christmastreenormaldark.dts",
		"christmastreesnowy" => "data/shapes/xmas/christmastreesnowy.dts",
		"christmastreesnowylong" => "data/shapes/xmas/christmastreesnowylong.dts",
		"giftcratenormalopen" => "data/shapes/xmas/giftcratenormalopen.dts",
		"giftcratebignormal" => "data/shapes/xmas/giftcratebignormal.dts",
		"giftcratenormalclosed" => "data/shapes/xmas/giftcratenormalclosed.dts",
		"giftcratenormal" => "data/shapes/xmas/giftboxnormal.dts",
		"giftcrateteared" => "data/shapes/xmas/giftboxteared.dts",
		"giftbooks" => "data/shapes/xmas/giftbooks.dts",
		"giftconsole" => "data/shapes/xmas/giftconsole.dts",
		"giftgame" => "data/shapes/xmas/giftgame.dts",
		"gifttv" => "data/shapes/xmas/gifttv.dts",
		"gingerbreadman" => "data/shapes/xmas/gingerbreadman.dts",
		"mistletoes" => "data/shapes/xmas/mistletoes.dts",
		"regularbush" => "data/shapes/xmas/regular_bush.dts",
		"snowybush" => "data/shapes/xmas/snowy_bush.dts",
		"snowballbig" => "data/shapes/xmas/snow_ball_big.dts",
		"snowballbigimperfect" => "data/shapes/xmas/snow_ball_big_imperfect.dts",
		"snowballpile" => "data/shapes/xmas/snow_ball_pile.dts",
		"snowballsmall" => "data/shapes/xmas/snow_ball_small.dts",
		"snowman" => "data/shapes/xmas/snowman.dts",
		"snowpatch1" => "data/shapes/xmas/snowpatch_1.dts",
		"snowpatch2" => "data/shapes/xmas/snowpatch_2.dts",
		"snowpatch3" => "data/shapes/xmas/snowpatch_3.dts",
		"snowpatch4" => "data/shapes/xmas/snowpatch_4.dts",
		"snowpatch5" => "data/shapes/xmas/snowpatch_5.dts",
		"snowpatch6" => "data/shapes/xmas/snowpatch_6.dts",
		"sockwgame" => "data/shapes/xmas/sockwgame.dts",
		"sockwgift" => "data/shapes/xmas/sockwgift.dts",
		"sockwnobody" => "data/shapes/xmas/sockwnobody.dts",
		"thegamebox" => "data/shapes/xmas/thegame_box.dts",

		// Water surfaces - purely visual (`server/scripts/water.cs`'s `Water` class); the ambient
		// wave animation plays automatically via the generic DTS sequence system, no special
		// handling needed. Gameplay effects come from the separate `WaterPhysicsTrigger` volume a
		// level author places on top. The "_slow" cylinder's z-scale-flatten quirk (`isScaled`) is
		// not reproduced - not worth bespoke `setTransform` machinery for a cosmetic edge case, and
		// the DTS has no collision mesh either way.
		"waterplane" => "data/shapes_pq/gameplay/water.dts",
		"watercylinder" => "data/shapes_pq/other/cylinderwater.dts",
		"watercylinder_slow" => "data/shapes_pq/other/cylinderwater_slow.dts",
	];
}
